name: Scheduled API Calls

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out eng_wales branch
      uses: actions/checkout@v2
      with:
        ref: eng_wales
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests opencage geocoder
    - name: Run the script
      run: python api_calls_ew.py
